import streamlit as st


#st.title("Projects")

#st.write("You have entered", st.session_state["my_input"])
#import streamlit as st
from PIL import Image
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
#from keras.preprocessing.image import load_img,img_to_array
import numpy as np
from keras.models import load_model


import sys
from streamlit.web import cli as stcli

import openpyxl as xl

wb=xl.load_workbook("E:/Bird_Species_Classification_Streamlit-master/personal/teja.xlsx")
ws=wb.active





import pandas as pd  # pip install pandas openpyxl
import plotly.express as px  # pip install plotly-express
import streamlit as st  # pip install streamlit
#import streamlit_authenticator as stauth  # pip install streamlit-authenticator

import sys 
import os
sys.path.append(os.path.abspath("C:/Bird_Species_Classification_Streamlit-master/personal/backuppages"))
# from backuppages import *
# import database as db
# import upload_to_database


# --- USER AUTHENTICATION ---
# users = db.fetch_all_users()

# usernames = [user["key"] for user in users]
# names = [user["name"] for user in users]
# hashed_passwords = [user["password"] for user in users]

# authenticator = stauth.Authenticate(names, usernames, hashed_passwords,
#     "sales_dashboard", "abcdef", cookie_expiry_days=30)

# name, authentication_status, username = authenticator.login("Login", "main")









if 5>4:
  import streamlit as st
  from PIL import Image
  #import keras
  from keras.preprocessing.image import load_img
  from keras.preprocessing.image import img_to_array
  #from keras.preprocessing.image import load_img,img_to_array
  import numpy as np
  from keras.models import load_model
  import sys
  from streamlit.web import cli as stcli

  model = load_model('D:\Bird_Species_Classification_Streamlit-master\personal\BCccc.h5',compile=False)
  #lab = {0: 'AFRICAN CROWNED CRANE', 1: 'AFRICAN FIREFINCH', 2: 'ALBATROSS', 3: 'ALEXANDRINE PARAKEET', 4: 'AMERICAN AVOCET', 5: 'AMERICAN BITTERN', 6: 'AMERICAN COOT', 7: 'AMERICAN GOLDFINCH', 8: 'AMERICAN KESTREL', 9: 'AMERICAN PIPIT', 10: 'AMERICAN REDSTART', 11: 'ANHINGA', 12: 'ANNAS HUMMINGBIRD', 13: 'ANTBIRD', 14: 'ARARIPE MANAKIN', 15: 'ASIAN CRESTED IBIS', 16: 'BALD EAGLE', 17: 'BALI STARLING', 18: 'BALTIMORE ORIOLE', 19: 'BANANAQUIT', 20: 'BANDED BROADBILL', 21: 'BAR-TAILED GODWIT', 22: 'BARN OWL', 23: 'BARN SWALLOW', 24: 'BARRED PUFFBIRD', 25: 'BAY-BREASTED WARBLER', 26: 'BEARDED BARBET', 27: 'BEARDED REEDLING', 28: 'BELTED KINGFISHER', 29: 'BIRD OF PARADISE', 30: 'BLACK & YELLOW bROADBILL', 31: 'BLACK FRANCOLIN', 32: 'BLACK SKIMMER', 33: 'BLACK SWAN', 34: 'BLACK TAIL CRAKE', 35: 'BLACK THROATED BUSHTIT', 36: 'BLACK THROATED WARBLER', 37: 'BLACK VULTURE', 38: 'BLACK-CAPPED CHICKADEE', 39: 'BLACK-NECKED GREBE', 40: 'BLACK-THROATED SPARROW', 41: 'BLACKBURNIAM WARBLER', 42: 'BLUE GROUSE', 43: 'BLUE HERON', 44: 'BOBOLINK', 45: 'BORNEAN BRISTLEHEAD', 46: 'BORNEAN LEAFBIRD', 47: 'BROWN NOODY', 48: 'BROWN THRASHER', 49: 'BULWERS PHEASANT', 50: 'CACTUS WREN', 51: 'CALIFORNIA CONDOR', 52: 'CALIFORNIA GULL', 53: 'CALIFORNIA QUAIL', 54: 'CANARY', 55: 'CAPE MAY WARBLER', 56: 'CAPUCHINBIRD', 57: 'CARMINE BEE-EATER', 58: 'CASPIAN TERN', 59: 'CASSOWARY', 60: 'CEDAR WAXWING', 61: 'CHARA DE COLLAR', 62: 'CHIPPING SPARROW', 63: 'CHUKAR PARTRIDGE', 64: 'CINNAMON TEAL', 65: 'COCK OF THE  ROCK', 66: 'COCKATOO', 67: 'COMMON FIRECREST', 68: 'COMMON GRACKLE', 69: 'COMMON HOUSE MARTIN', 70: 'COMMON LOON', 71: 'COMMON POORWILL', 72: 'COMMON STARLING', 73: 'COUCHS KINGBIRD', 74: 'CRESTED AUKLET', 75: 'CRESTED CARACARA', 76: 'CRESTED NUTHATCH', 77: 'CROW', 78: 'CROWNED PIGEON', 79: 'CUBAN TODY', 80: 'CURL CRESTED ARACURI', 81: 'D-ARNAUDS BARBET', 82: 'DARK EYED JUNCO', 83: 'DOUBLE BARRED FINCH', 84: 'DOWNY WOODPECKER', 85: 'EASTERN BLUEBIRD', 86: 'EASTERN MEADOWLARK', 87: 'EASTERN ROSELLA', 88: 'EASTERN TOWEE', 89: 'ELEGANT TROGON', 90: 'ELLIOTS  PHEASANT', 91: 'EMPEROR PENGUIN', 92: 'EMU', 93: 'ENGGANO MYNA', 94: 'EURASIAN GOLDEN ORIOLE', 95: 'EURASIAN MAGPIE', 96: 'EVENING GROSBEAK', 97: 'FIRE TAILLED MYZORNIS', 98: 'FLAME TANAGER', 99: 'FLAMINGO', 100: 'FRIGATE', 101: 'GAMBELS QUAIL', 102: 'GANG GANG COCKATOO', 103: 'GILA WOODPECKER', 104: 'GILDED FLICKER', 105: 'GLOSSY IBIS', 106: 'GO AWAY BIRD', 107: 'GOLD WING WARBLER', 108: 'GOLDEN CHEEKED WARBLER', 109: 'GOLDEN CHLOROPHONIA', 110: 'GOLDEN EAGLE', 111: 'GOLDEN PHEASANT', 112: 'GOLDEN PIPIT', 113: 'GOULDIAN FINCH', 114: 'GRAY CATBIRD', 115: 'GRAY PARTRIDGE', 116: 'GREAT POTOO', 117: 'GREATOR SAGE GROUSE', 118: 'GREEN JAY', 119: 'GREEN MAGPIE', 120: 'GREY PLOVER', 121: 'GUINEA TURACO', 122: 'GUINEAFOWL', 123: 'GYRFALCON', 124: 'HARPY EAGLE', 125: 'HAWAIIAN GOOSE', 126: 'HELMET VANGA', 127: 'HIMALAYAN MONAL', 128: 'HOATZIN', 129: 'HOODED MERGANSER', 130: 'HOOPOES', 131: 'HORNBILL', 132: 'HORNED GUAN', 133: 'HORNED SUNGEM', 134: 'HOUSE FINCH', 135: 'HOUSE SPARROW', 136: 'IMPERIAL SHAQ', 137: 'INCA TERN', 138: 'INDIAN BUSTARD', 139: 'INDIAN PITTA', 140: 'INDIGO BUNTING', 141: 'JABIRU', 142: 'JAVA SPARROW', 143: 'KAKAPO', 144: 'KILLDEAR', 145: 'KING VULTURE', 146: 'KIWI', 147: 'KOOKABURRA', 148: 'LARK BUNTING', 149: 'LEARS MACAW', 150: 'LILAC ROLLER', 151: 'LONG-EARED OWL', 152: 'MAGPIE GOOSE', 153: 'MALABAR HORNBILL', 154: 'MALACHITE KINGFISHER', 155: 'MALEO', 156: 'MALLARD DUCK', 157: 'MANDRIN DUCK', 158: 'MARABOU STORK', 159: 'MASKED BOOBY', 160: 'MASKED LAPWING', 161: 'MIKADO  PHEASANT', 162: 'MOURNING DOVE', 163: 'MYNA', 164: 'NICOBAR PIGEON', 165: 'NOISY FRIARBIRD', 166: 'NORTHERN BALD IBIS', 167: 'NORTHERN CARDINAL', 168: 'NORTHERN FLICKER', 169: 'NORTHERN GANNET', 170: 'NORTHERN GOSHAWK', 171: 'NORTHERN JACANA', 172: 'NORTHERN MOCKINGBIRD', 173: 'NORTHERN PARULA', 174: 'NORTHERN RED BISHOP', 175: 'NORTHERN SHOVELER', 176: 'OCELLATED TURKEY', 177: 'OKINAWA RAIL', 178: 'OSPREY', 179: 'OSTRICH', 180: 'OYSTER CATCHER', 181: 'PAINTED BUNTIG', 182: 'PALILA', 183: 'PARADISE TANAGER', 184: 'PARUS MAJOR', 185: 'PEACOCK \n This animal is national bird of india', 186: 'PELICAN', 187: 'PEREGRINE FALCON', 188: 'PHILIPPINE EAGLE', 189: 'PINK ROBIN', 190: 'PUFFIN', 191: 'PURPLE FINCH', 192: 'PURPLE GALLINULE', 193: 'PURPLE MARTIN', 194: 'PURPLE SWAMPHEN', 195: 'QUETZAL', 196: 'RAINBOW LORIKEET', 197: 'RAZORBILL', 198: 'RED BEARDED BEE EATER', 199: 'RED BELLIED PITTA', 200: 'RED BROWED FINCH', 201: 'RED FACED CORMORANT', 202: 'RED FACED WARBLER', 203: 'RED HEADED DUCK', 204: 'RED HEADED WOODPECKER', 205: 'RED HONEY CREEPER', 206: 'RED TAILED THRUSH', 207: 'RED WINGED BLACKBIRD', 208: 'RED WISKERED BULBUL', 209: 'REGENT BOWERBIRD', 210: 'RING-NECKED PHEASANT', 211: 'ROADRUNNER', 212: 'ROBIN', 213: 'ROCK DOVE', 214: 'ROSY FACED LOVEBIRD', 215: 'ROUGH LEG BUZZARD', 216: 'ROYAL FLYCATCHER', 217: 'RUBY THROATED HUMMINGBIRD', 218: 'RUFOUS KINGFISHER', 219: 'RUFUOS MOTMOT', 220: 'SAMATRAN THRUSH', 221: 'SAND MARTIN', 222: 'SCARLET IBIS', 223: 'SCARLET MACAW', 224: 'SHOEBILL', 225: 'SHORT BILLED DOWITCHER', 226: 'SMITHS LONGSPUR', 227: 'SNOWY EGRET', 228: 'SNOWY OWL', 229: 'SORA', 230: 'SPANGLED COTINGA', 231: 'SPLENDID WREN', 232: 'SPOON BILED SANDPIPER', 233: 'SPOONBILL', 234: 'SRI LANKA BLUE MAGPIE', 235: 'STEAMER DUCK', 236: 'STORK BILLED KINGFISHER', 237: 'STRAWBERRY FINCH', 238: 'STRIPPED SWALLOW', 239: 'SUPERB STARLING', 240: 'SWINHOES PHEASANT', 241: 'TAIWAN MAGPIE', 242: 'TAKAHE', 243: 'TASMANIAN HEN', 244: 'TEAL DUCK', 245: 'TIT MOUSE', 246: 'TOUCHAN', 247: 'TOWNSENDS WARBLER', 248: 'TREE SWALLOW', 249: 'TRUMPTER SWAN', 250: 'TURKEY VULTURE', 251: 'TURQUOISE MOTMOT', 252: 'UMBRELLA BIRD', 253: 'VARIED THRUSH', 254: 'VENEZUELIAN TROUPIAL', 255: 'VERMILION FLYCATHER', 256: 'VICTORIA CROWNED PIGEON', 257: 'VIOLET GREEN SWALLOW', 258: 'VULTURINE GUINEAFOWL', 259: 'WATTLED CURASSOW', 260: 'WHIMBREL', 261: 'WHITE CHEEKED TURACO', 262: 'WHITE NECKED RAVEN', 263: 'WHITE TAILED TROPIC', 264: 'WILD TURKEY', 265: 'WILSONS BIRD OF PARADISE', 266: 'WOOD DUCK', 267: 'YELLOW BELLIED FLOWERPECKER', 268: 'YELLOW CACIQUE', 269: 'YELLOW HEADED BLACKBIRD'}
  lab = {0: 'ABBOTTS BABBLER', 1: 'ABBOTTS BOOBY', 2: 'ABYSSINIAN GROUND HORNBILL', 3: 'AFRICAN CROWNED CRANE', 4: 'AFRICAN EMERALD CUCKOO', 5: 'AFRICAN FIREFINCH', 6: 'AFRICAN OYSTER CATCHER', 7: 'ALBATROSS', 8: 'ALBERTS TOWHEE', 9: 'ALEXANDRINE PARAKEET', 10: 'ALPINE CHOUGH', 11: 'ALTAMIRA YELLOWTHROAT', 12: 'AMERICAN AVOCET', 13: 'AMERICAN BITTERN', 14: 'AMERICAN COOT', 15: 'AMERICAN GOLDFINCH', 16: 'AMERICAN KESTREL', 17: 'AMERICAN PIPIT', 18: 'AMERICAN REDSTART', 19: 'AMETHYST WOODSTAR', 20: 'ANDEAN GOOSE', 21: 'ANDEAN LAPWING', 22: 'ANDEAN SISKIN', 23: 'ANHINGA', 24: 'ANIANIAU', 25: 'ANNAS HUMMINGBIRD', 26: 'ANTBIRD', 27: 'ANTILLEAN EUPHONIA', 28: 'APAPANE', 29: 'APOSTLEBIRD', 30: 'ARARIPE MANAKIN', 31: 'ASHY THRUSHBIRD', 32: 'ASIAN CRESTED IBIS', 33: 'AVADAVAT', 34: 'AZURE JAY', 35: 'AZURE TANAGER', 36: 'AZURE TIT', 37: 'BAIKAL TEAL', 38: 'BALD EAGLE', 39: 'BALD IBIS', 40: 'BALI STARLING', 41: 'BALTIMORE ORIOLE', 42: 'BANANAQUIT', 43: 'BAND TAILED GUAN', 44: 'BANDED BROADBILL', 45: 'BANDED PITA', 46: 'BANDED STILT', 47: 'BAR-TAILED GODWIT', 48: 'BARN OWL', 49: 'BARN SWALLOW', 50: 'BARRED PUFFBIRD', 51: 'BARROWS GOLDENEYE', 52: 'BAY-BREASTED WARBLER', 53: 'BEARDED BARBET', 54: 'BEARDED BELLBIRD', 55: 'BEARDED REEDLING', 56: 'BELTED KINGFISHER', 57: 'BIRD OF PARADISE', 58: 'BLACK & YELLOW  BROADBILL', 59: 'BLACK BAZA', 60: 'BLACK COCKATO', 61: 'BLACK FRANCOLIN', 62: 'BLACK SKIMMER', 63: 'BLACK SWAN', 64: 'BLACK TAIL CRAKE', 65: 'BLACK THROATED BUSHTIT', 66: 'BLACK THROATED WARBLER', 67: 'BLACK VULTURE', 68: 'BLACK-CAPPED CHICKADEE', 69: 'BLACK-NECKED GREBE', 70: 'BLACK-THROATED SPARROW', 71: 'BLACKBURNIAM WARBLER', 72: 'BLONDE CRESTED WOODPECKER', 73: 'BLUE COAU', 74: 'BLUE GROUSE', 75: 'BLUE HERON', 76: 'BLUE THROATED TOUCANET', 77: 'BOBOLINK', 78: 'BORNEAN BRISTLEHEAD', 79: 'BORNEAN LEAFBIRD', 80: 'BORNEAN PHEASANT', 81: 'BRANDT CORMARANT', 82: 'BROWN CREPPER', 83: 'BROWN NOODY', 84: 'BROWN THRASHER', 85: 'BULWERS PHEASANT', 86: 'BUSH TURKEY', 87: 'CACTUS WREN', 88: 'CALIFORNIA CONDOR', 89: 'CALIFORNIA GULL', 90: 'CALIFORNIA QUAIL', 91: 'CANARY', 92: 'CAPE GLOSSY STARLING', 93: 'CAPE LONGCLAW', 94: 'CAPE MAY WARBLER', 95: 'CAPE ROCK THRUSH', 96: 'CAPPED HERON', 97: 'CAPUCHINBIRD', 98: 'CARMINE BEE-EATER', 99: 'CASPIAN TERN', 100: 'CASSOWARY', 101: 'CEDAR WAXWING', 102: 'CERULEAN WARBLER', 103: 'CHARA DE COLLAR', 104: 'CHATTERING LORY', 105: 'CHESTNET BELLIED EUPHONIA', 106: 'CHINESE BAMBOO PARTRIDGE', 107: 'CHINESE POND HERON', 108: 'CHIPPING SPARROW', 109: 'CHUCAO TAPACULO', 110: 'CHUKAR PARTRIDGE', 111: 'CINNAMON ATTILA', 112: 'CINNAMON FLYCATCHER', 113: 'CINNAMON TEAL', 114: 'CLARKS NUTCRACKER', 115: 'COCK OF THE  ROCK', 116: 'COCKATOO', 117: 'COLLARED ARACARI', 118: 'COMMON FIRECREST', 119: 'COMMON GRACKLE', 120: 'COMMON HOUSE MARTIN', 121: 'COMMON IORA', 122: 'COMMON LOON', 123: 'COMMON POORWILL', 124: 'COMMON STARLING', 125: 'COPPERY TAILED COUCAL', 126: 'CRAB PLOVER', 127: 'CRANE HAWK', 128: 'CREAM COLORED WOODPECKER', 129: 'CRESTED AUKLET', 130: 'CRESTED CARACARA', 131: 'CRESTED COUA', 132: 'CRESTED FIREBACK', 133: 'CRESTED KINGFISHER', 134: 'CRESTED NUTHATCH', 135: 'CRESTED OROPENDOLA', 136: 'CRESTED SHRIKETIT', 137: 'CRIMSON CHAT', 138: 'CRIMSON SUNBIRD', 139: 'CROW', 140: 'CROWNED PIGEON', 141: 'CUBAN TODY', 142: 'CUBAN TROGON', 143: 'CURL CRESTED ARACURI', 144: 'D-ARNAUDS BARBET', 145: 'DARK EYED JUNCO', 146: 'DEMOISELLE CRANE', 147: 'DOUBLE BARRED FINCH', 148: 'DOUBLE BRESTED CORMARANT', 149: 'DOUBLE EYED FIG PARROT', 150: 'DOWNY WOODPECKER', 151: 'DUSKY LORY', 152: 'EARED PITA', 153: 'EASTERN BLUEBIRD', 154: 'EASTERN GOLDEN WEAVER', 155: 'EASTERN MEADOWLARK', 156: 'EASTERN ROSELLA', 157: 'EASTERN TOWEE', 158: 'ELEGANT TROGON', 159: 'ELLIOTS  PHEASANT', 160: 'EMERALD TANAGER', 161: 'EMPEROR PENGUIN', 162: 'EMU', 163: 'ENGGANO MYNA', 164: 'EURASIAN GOLDEN ORIOLE', 165: 'EURASIAN MAGPIE', 166: 'EUROPEAN GOLDFINCH', 167: 'EUROPEAN TURTLE DOVE', 168: 'EVENING GROSBEAK', 169: 'FAIRY BLUEBIRD', 170: 'FAIRY TERN', 171: 'FIORDLAND PENGUIN', 172: 'FIRE TAILLED MYZORNIS', 173: 'FLAME BOWERBIRD', 174: 'FLAME TANAGER', 175: 'FLAMINGO', 176: 'FRIGATE', 177: 'GAMBELS QUAIL', 178: 'GANG GANG COCKATOO', 179: 'GILA WOODPECKER', 180: 'GILDED FLICKER', 181: 'GLOSSY IBIS', 182: 'GO AWAY BIRD', 183: 'GOLD WING WARBLER', 184: 'GOLDEN CHEEKED WARBLER', 185: 'GOLDEN CHLOROPHONIA', 186: 'GOLDEN EAGLE', 187: 'GOLDEN PHEASANT', 188: 'GOLDEN PIPIT', 189: 'GOULDIAN FINCH', 190: 'GRAY CATBIRD', 191: 'GRAY KINGBIRD', 192: 'GRAY PARTRIDGE', 193: 'GREAT GRAY OWL', 194: 'GREAT JACAMAR', 195: 'GREAT KISKADEE', 196: 'GREAT POTOO', 197: 'GREATOR SAGE GROUSE', 198: 'GREEN BROADBILL', 199: 'GREEN JAY', 200: 'GREEN MAGPIE', 201: 'GREY PLOVER', 202: 'GROVED BILLED ANI', 203: 'GUINEA TURACO', 204: 'GUINEAFOWL', 205: 'GURNEYS PITTA', 206: 'GYRFALCON', 207: 'HAMMERKOP', 208: 'HARLEQUIN DUCK', 209: 'HARLEQUIN QUAIL', 210: 'HARPY EAGLE', 211: 'HAWAIIAN GOOSE', 212: 'HAWFINCH', 213: 'HELMET VANGA', 214: 'HEPATIC TANAGER', 215: 'HIMALAYAN BLUETAIL', 216: 'HIMALAYAN MONAL', 217: 'HOATZIN', 218: 'HOODED MERGANSER', 219: 'HOOPOES', 220: 'HORNBILL', 221: 'HORNED GUAN', 222: 'HORNED LARK', 223: 'HORNED SUNGEM', 224: 'HOUSE FINCH', 225: 'HOUSE SPARROW', 226: 'HYACINTH MACAW', 227: 'IBERIAN MAGPIE', 228: 'IBISBILL', 229: 'IMPERIAL SHAQ', 230: 'INCA TERN', 231: 'INDIAN BUSTARD', 232: 'INDIAN PITTA', 233: 'INDIAN ROLLER', 234: 'INDIGO BUNTING', 235: 'INLAND DOTTEREL', 236: 'IVORY GULL', 237: 'IWI', 238: 'JABIRU', 239: 'JACK SNIPE', 240: 'JANDAYA PARAKEET', 241: 'JAPANESE ROBIN', 242: 'JAVA SPARROW', 243: 'KAGU', 244: 'KAKAPO', 245: 'KILLDEAR', 246: 'KING VULTURE', 247: 'KIWI', 248: 'KOOKABURRA', 249: 'LARK BUNTING', 250: 'LAZULI BUNTING', 251: 'LESSER ADJUTANT', 252: 'LILAC ROLLER', 253: 'LITTLE AUK', 254: 'LONG-EARED OWL', 255: 'MAGPIE GOOSE', 256: 'MALABAR HORNBILL', 257: 'MALACHITE KINGFISHER', 258: 'MALAGASY WHITE EYE', 259: 'MALEO', 260: 'MALLARD DUCK', 261: 'MANDRIN DUCK', 262: 'MANGROVE CUCKOO', 263: 'MARABOU STORK', 264: 'MASKED BOOBY', 265: 'MASKED LAPWING', 266: 'MIKADO  PHEASANT', 267: 'MOURNING DOVE', 268: 'MYNA', 269: 'NICOBAR PIGEON', 270: 'NOISY FRIARBIRD', 271: 'NORTHERN CARDINAL', 272: 'NORTHERN FLICKER', 273: 'NORTHERN FULMAR', 274: 'NORTHERN GANNET', 275: 'NORTHERN GOSHAWK', 276: 'NORTHERN JACANA', 277: 'NORTHERN MOCKINGBIRD', 278: 'NORTHERN PARULA', 279: 'NORTHERN RED BISHOP', 280: 'NORTHERN SHOVELER', 281: 'OCELLATED TURKEY', 282: 'OKINAWA RAIL', 283: 'ORANGE BRESTED BUNTING', 284: 'ORIENTAL BAY OWL', 285: 'OSPREY', 286: 'OSTRICH', 287: 'OVENBIRD', 288: 'OYSTER CATCHER', 289: 'PAINTED BUNTING', 290: 'PALILA', 291: 'PARADISE TANAGER', 292: 'PARAKETT  AKULET', 293: 'PARUS MAJOR', 294: 'PATAGONIAN SIERRA FINCH', 295: 'PEACOCK', 296: 'PELICAN', 297: 'PEREGRINE FALCON', 298: 'PHILIPPINE EAGLE', 299: 'PINK ROBIN', 300: 'POMARINE JAEGER', 301: 'PUFFIN', 302: 'PURPLE FINCH', 303: 'PURPLE GALLINULE', 304: 'PURPLE MARTIN', 305: 'PURPLE SWAMPHEN', 306: 'PYGMY KINGFISHER', 307: 'QUETZAL', 308: 'RAINBOW LORIKEET', 309: 'RAZORBILL', 310: 'RED BEARDED BEE EATER', 311: 'RED BELLIED PITTA', 312: 'RED BROWED FINCH', 313: 'RED FACED CORMORANT', 314: 'RED FACED WARBLER', 315: 'RED FODY', 316: 'RED HEADED DUCK', 317: 'RED HEADED WOODPECKER', 318: 'RED HONEY CREEPER', 319: 'RED NAPED TROGON', 320: 'RED TAILED HAWK', 321: 'RED TAILED THRUSH', 322: 'RED WINGED BLACKBIRD', 323: 'RED WISKERED BULBUL', 324: 'REGENT BOWERBIRD', 325: 'RING-NECKED PHEASANT', 326: 'ROADRUNNER', 327: 'ROBIN', 328: 'ROCK DOVE', 329: 'ROSY FACED LOVEBIRD', 330: 'ROUGH LEG BUZZARD', 331: 'ROYAL FLYCATCHER', 332: 'RUBY THROATED HUMMINGBIRD', 333: 'RUDY KINGFISHER', 334: 'RUFOUS KINGFISHER', 335: 'RUFUOS MOTMOT', 336: 'SAMATRAN THRUSH', 337: 'SAND MARTIN', 338: 'SANDHILL CRANE', 339: 'SATYR TRAGOPAN', 340: 'SCARLET CROWNED FRUIT DOVE', 341: 'SCARLET IBIS', 342: 'SCARLET MACAW', 343: 'SCARLET TANAGER', 344: 'SHOEBILL', 345: 'SHORT BILLED DOWITCHER', 346: 'SMITHS LONGSPUR', 347: 'SNOWY EGRET', 348: 'SNOWY OWL', 349: 'SORA', 350: 'SPANGLED COTINGA', 351: 'SPLENDID WREN', 352: 'SPOON BILED SANDPIPER', 353: 'SPOONBILL', 354: 'SPOTTED CATBIRD', 355: 'SRI LANKA BLUE MAGPIE', 356: 'STEAMER DUCK', 357: 'STORK BILLED KINGFISHER', 358: 'STRAWBERRY FINCH', 359: 'STRIPED OWL', 360: 'STRIPPED MANAKIN', 361: 'STRIPPED SWALLOW', 362: 'SUPERB STARLING', 363: 'SWINHOES PHEASANT', 364: 'TAILORBIRD', 365: 'TAIWAN MAGPIE', 366: 'TAKAHE', 367: 'TASMANIAN HEN', 368: 'TEAL DUCK', 369: 'TIT MOUSE', 370: 'TOUCHAN', 371: 'TOWNSENDS WARBLER', 372: 'TREE SWALLOW', 373: 'TROPICAL KINGBIRD', 374: 'TRUMPTER SWAN', 375: 'TURKEY VULTURE', 376: 'TURQUOISE MOTMOT', 377: 'UMBRELLA BIRD', 378: 'VARIED THRUSH', 379: 'VENEZUELIAN TROUPIAL', 380: 'VERMILION FLYCATHER', 381: 'VICTORIA CROWNED PIGEON', 382: 'VIOLET GREEN SWALLOW', 383: 'VIOLET TURACO', 384: 'VULTURINE GUINEAFOWL', 385: 'WALL CREAPER', 386: 'WATTLED CURASSOW', 387: 'WATTLED LAPWING', 388: 'WHIMBREL', 389: 'WHITE BROWED CRAKE', 390: 'WHITE CHEEKED TURACO', 391: 'WHITE NECKED RAVEN', 392: 'WHITE TAILED TROPIC', 393: 'WHITE THROATED BEE EATER', 394: 'WILD TURKEY', 395: 'WILSONS BIRD OF PARADISE', 396: 'WOOD DUCK', 397: 'YELLOW BELLIED FLOWERPECKER', 398: 'YELLOW CACIQUE', 399: 'YELLOW HEADED BLACKBIRD'}
  def processed_img(img_path):
    img=load_img(img_path,target_size=(224,224,300))
    img=img_to_array(img)
    img=img/255
    img=np.expand_dims(img,[0])
    answer=model.predict(img)
    y_class = answer.argmax(axis=-1)
    print(y_class)
    y = " ".join(str(x) for x in y_class)
    y = int(y)
    res = lab[y]
    print(res)
    return res

  def run():
    # import database
    # import upload_to_database   
    img1 = Image.open('./meta/logo1.png')
    img1 = img1.resize((350,350))
    st.image(img1,use_column_width=False)
    st.title("Birds Species Classification")
    st.markdown('''<h4 style='text-align: left; color: #d73b5c;'>* Data is based "400+ Bird Species also see 70 Sports Dataset"</h4>''',
                unsafe_allow_html=True)

    img_file = st.file_uploader("Choose an Image of Bird", type=["jpg", "png","jpeg"])
    if img_file is not None:
        st.image(img_file,use_column_width=False)
        save_image_path = './upload_images/'+img_file.name
        with open(save_image_path, "wb") as f:
            f.write(img_file.getbuffer())

        if st.button("Predict"):
            result = processed_img(save_image_path)
            st.success("Predicted Bird is: "+result)
            for i in ws.iter_rows(max_row=ws.max_row,max_col=ws.max_column):
              if result==i[0].value:
                st.write("Scientific Name is  :"+i[1].value)
                if(i[2].value == None):
                  break
                st.write("Conservation status :"+i[2].value)
                st.write("Wingspan :"+i[3].value)
                st.write("Prey :"+i[4].value)
                st.write("Habitat :"  +i[5].value)
                # st.write("# Hello *world**")
        

    
  run()
  # authenticator.logout("Logout", "sidebar")
  st.sidebar.title(f"Hello There👋...")
  st.sidebar.header("Experimental analysis on dataset (i.e. Caltech-UCSD Birds 200 [CUB-200-2011]) shows that algorithm achieves an accuracy of bird identification between 80% and 90%.The experimental study is done with the Windows 11 operating system using a Tensor flow library")


    # ---- HIDE STREAMLIT STYLE ----
  hide_st_style = """
                <style>
                #MainMenu {visibility: hidden;}
                footer {visibility: hidden;}
                header {visibility: hidden;}
                </style>
                """
  st.markdown(hide_st_style, unsafe_allow_html=True)










# model = load_model('C:\Bird_Species_Classification_Streamlit-master\BCccc.h5',compile=False)
# #lab = {0: 'AFRICAN CROWNED CRANE', 1: 'AFRICAN FIREFINCH', 2: 'ALBATROSS', 3: 'ALEXANDRINE PARAKEET', 4: 'AMERICAN AVOCET', 5: 'AMERICAN BITTERN', 6: 'AMERICAN COOT', 7: 'AMERICAN GOLDFINCH', 8: 'AMERICAN KESTREL', 9: 'AMERICAN PIPIT', 10: 'AMERICAN REDSTART', 11: 'ANHINGA', 12: 'ANNAS HUMMINGBIRD', 13: 'ANTBIRD', 14: 'ARARIPE MANAKIN', 15: 'ASIAN CRESTED IBIS', 16: 'BALD EAGLE', 17: 'BALI STARLING', 18: 'BALTIMORE ORIOLE', 19: 'BANANAQUIT', 20: 'BANDED BROADBILL', 21: 'BAR-TAILED GODWIT', 22: 'BARN OWL', 23: 'BARN SWALLOW', 24: 'BARRED PUFFBIRD', 25: 'BAY-BREASTED WARBLER', 26: 'BEARDED BARBET', 27: 'BEARDED REEDLING', 28: 'BELTED KINGFISHER', 29: 'BIRD OF PARADISE', 30: 'BLACK & YELLOW bROADBILL', 31: 'BLACK FRANCOLIN', 32: 'BLACK SKIMMER', 33: 'BLACK SWAN', 34: 'BLACK TAIL CRAKE', 35: 'BLACK THROATED BUSHTIT', 36: 'BLACK THROATED WARBLER', 37: 'BLACK VULTURE', 38: 'BLACK-CAPPED CHICKADEE', 39: 'BLACK-NECKED GREBE', 40: 'BLACK-THROATED SPARROW', 41: 'BLACKBURNIAM WARBLER', 42: 'BLUE GROUSE', 43: 'BLUE HERON', 44: 'BOBOLINK', 45: 'BORNEAN BRISTLEHEAD', 46: 'BORNEAN LEAFBIRD', 47: 'BROWN NOODY', 48: 'BROWN THRASHER', 49: 'BULWERS PHEASANT', 50: 'CACTUS WREN', 51: 'CALIFORNIA CONDOR', 52: 'CALIFORNIA GULL', 53: 'CALIFORNIA QUAIL', 54: 'CANARY', 55: 'CAPE MAY WARBLER', 56: 'CAPUCHINBIRD', 57: 'CARMINE BEE-EATER', 58: 'CASPIAN TERN', 59: 'CASSOWARY', 60: 'CEDAR WAXWING', 61: 'CHARA DE COLLAR', 62: 'CHIPPING SPARROW', 63: 'CHUKAR PARTRIDGE', 64: 'CINNAMON TEAL', 65: 'COCK OF THE  ROCK', 66: 'COCKATOO', 67: 'COMMON FIRECREST', 68: 'COMMON GRACKLE', 69: 'COMMON HOUSE MARTIN', 70: 'COMMON LOON', 71: 'COMMON POORWILL', 72: 'COMMON STARLING', 73: 'COUCHS KINGBIRD', 74: 'CRESTED AUKLET', 75: 'CRESTED CARACARA', 76: 'CRESTED NUTHATCH', 77: 'CROW', 78: 'CROWNED PIGEON', 79: 'CUBAN TODY', 80: 'CURL CRESTED ARACURI', 81: 'D-ARNAUDS BARBET', 82: 'DARK EYED JUNCO', 83: 'DOUBLE BARRED FINCH', 84: 'DOWNY WOODPECKER', 85: 'EASTERN BLUEBIRD', 86: 'EASTERN MEADOWLARK', 87: 'EASTERN ROSELLA', 88: 'EASTERN TOWEE', 89: 'ELEGANT TROGON', 90: 'ELLIOTS  PHEASANT', 91: 'EMPEROR PENGUIN', 92: 'EMU', 93: 'ENGGANO MYNA', 94: 'EURASIAN GOLDEN ORIOLE', 95: 'EURASIAN MAGPIE', 96: 'EVENING GROSBEAK', 97: 'FIRE TAILLED MYZORNIS', 98: 'FLAME TANAGER', 99: 'FLAMINGO', 100: 'FRIGATE', 101: 'GAMBELS QUAIL', 102: 'GANG GANG COCKATOO', 103: 'GILA WOODPECKER', 104: 'GILDED FLICKER', 105: 'GLOSSY IBIS', 106: 'GO AWAY BIRD', 107: 'GOLD WING WARBLER', 108: 'GOLDEN CHEEKED WARBLER', 109: 'GOLDEN CHLOROPHONIA', 110: 'GOLDEN EAGLE', 111: 'GOLDEN PHEASANT', 112: 'GOLDEN PIPIT', 113: 'GOULDIAN FINCH', 114: 'GRAY CATBIRD', 115: 'GRAY PARTRIDGE', 116: 'GREAT POTOO', 117: 'GREATOR SAGE GROUSE', 118: 'GREEN JAY', 119: 'GREEN MAGPIE', 120: 'GREY PLOVER', 121: 'GUINEA TURACO', 122: 'GUINEAFOWL', 123: 'GYRFALCON', 124: 'HARPY EAGLE', 125: 'HAWAIIAN GOOSE', 126: 'HELMET VANGA', 127: 'HIMALAYAN MONAL', 128: 'HOATZIN', 129: 'HOODED MERGANSER', 130: 'HOOPOES', 131: 'HORNBILL', 132: 'HORNED GUAN', 133: 'HORNED SUNGEM', 134: 'HOUSE FINCH', 135: 'HOUSE SPARROW', 136: 'IMPERIAL SHAQ', 137: 'INCA TERN', 138: 'INDIAN BUSTARD', 139: 'INDIAN PITTA', 140: 'INDIGO BUNTING', 141: 'JABIRU', 142: 'JAVA SPARROW', 143: 'KAKAPO', 144: 'KILLDEAR', 145: 'KING VULTURE', 146: 'KIWI', 147: 'KOOKABURRA', 148: 'LARK BUNTING', 149: 'LEARS MACAW', 150: 'LILAC ROLLER', 151: 'LONG-EARED OWL', 152: 'MAGPIE GOOSE', 153: 'MALABAR HORNBILL', 154: 'MALACHITE KINGFISHER', 155: 'MALEO', 156: 'MALLARD DUCK', 157: 'MANDRIN DUCK', 158: 'MARABOU STORK', 159: 'MASKED BOOBY', 160: 'MASKED LAPWING', 161: 'MIKADO  PHEASANT', 162: 'MOURNING DOVE', 163: 'MYNA', 164: 'NICOBAR PIGEON', 165: 'NOISY FRIARBIRD', 166: 'NORTHERN BALD IBIS', 167: 'NORTHERN CARDINAL', 168: 'NORTHERN FLICKER', 169: 'NORTHERN GANNET', 170: 'NORTHERN GOSHAWK', 171: 'NORTHERN JACANA', 172: 'NORTHERN MOCKINGBIRD', 173: 'NORTHERN PARULA', 174: 'NORTHERN RED BISHOP', 175: 'NORTHERN SHOVELER', 176: 'OCELLATED TURKEY', 177: 'OKINAWA RAIL', 178: 'OSPREY', 179: 'OSTRICH', 180: 'OYSTER CATCHER', 181: 'PAINTED BUNTIG', 182: 'PALILA', 183: 'PARADISE TANAGER', 184: 'PARUS MAJOR', 185: 'PEACOCK \n This animal is national bird of india', 186: 'PELICAN', 187: 'PEREGRINE FALCON', 188: 'PHILIPPINE EAGLE', 189: 'PINK ROBIN', 190: 'PUFFIN', 191: 'PURPLE FINCH', 192: 'PURPLE GALLINULE', 193: 'PURPLE MARTIN', 194: 'PURPLE SWAMPHEN', 195: 'QUETZAL', 196: 'RAINBOW LORIKEET', 197: 'RAZORBILL', 198: 'RED BEARDED BEE EATER', 199: 'RED BELLIED PITTA', 200: 'RED BROWED FINCH', 201: 'RED FACED CORMORANT', 202: 'RED FACED WARBLER', 203: 'RED HEADED DUCK', 204: 'RED HEADED WOODPECKER', 205: 'RED HONEY CREEPER', 206: 'RED TAILED THRUSH', 207: 'RED WINGED BLACKBIRD', 208: 'RED WISKERED BULBUL', 209: 'REGENT BOWERBIRD', 210: 'RING-NECKED PHEASANT', 211: 'ROADRUNNER', 212: 'ROBIN', 213: 'ROCK DOVE', 214: 'ROSY FACED LOVEBIRD', 215: 'ROUGH LEG BUZZARD', 216: 'ROYAL FLYCATCHER', 217: 'RUBY THROATED HUMMINGBIRD', 218: 'RUFOUS KINGFISHER', 219: 'RUFUOS MOTMOT', 220: 'SAMATRAN THRUSH', 221: 'SAND MARTIN', 222: 'SCARLET IBIS', 223: 'SCARLET MACAW', 224: 'SHOEBILL', 225: 'SHORT BILLED DOWITCHER', 226: 'SMITHS LONGSPUR', 227: 'SNOWY EGRET', 228: 'SNOWY OWL', 229: 'SORA', 230: 'SPANGLED COTINGA', 231: 'SPLENDID WREN', 232: 'SPOON BILED SANDPIPER', 233: 'SPOONBILL', 234: 'SRI LANKA BLUE MAGPIE', 235: 'STEAMER DUCK', 236: 'STORK BILLED KINGFISHER', 237: 'STRAWBERRY FINCH', 238: 'STRIPPED SWALLOW', 239: 'SUPERB STARLING', 240: 'SWINHOES PHEASANT', 241: 'TAIWAN MAGPIE', 242: 'TAKAHE', 243: 'TASMANIAN HEN', 244: 'TEAL DUCK', 245: 'TIT MOUSE', 246: 'TOUCHAN', 247: 'TOWNSENDS WARBLER', 248: 'TREE SWALLOW', 249: 'TRUMPTER SWAN', 250: 'TURKEY VULTURE', 251: 'TURQUOISE MOTMOT', 252: 'UMBRELLA BIRD', 253: 'VARIED THRUSH', 254: 'VENEZUELIAN TROUPIAL', 255: 'VERMILION FLYCATHER', 256: 'VICTORIA CROWNED PIGEON', 257: 'VIOLET GREEN SWALLOW', 258: 'VULTURINE GUINEAFOWL', 259: 'WATTLED CURASSOW', 260: 'WHIMBREL', 261: 'WHITE CHEEKED TURACO', 262: 'WHITE NECKED RAVEN', 263: 'WHITE TAILED TROPIC', 264: 'WILD TURKEY', 265: 'WILSONS BIRD OF PARADISE', 266: 'WOOD DUCK', 267: 'YELLOW BELLIED FLOWERPECKER', 268: 'YELLOW CACIQUE', 269: 'YELLOW HEADED BLACKBIRD'}
# lab = {0: 'ABBOTTS BABBLER', 1: 'ABBOTTS BOOBY', 2: 'ABYSSINIAN GROUND HORNBILL', 3: 'AFRICAN CROWNED CRANE', 4: 'AFRICAN EMERALD CUCKOO', 5: 'AFRICAN FIREFINCH', 6: 'AFRICAN OYSTER CATCHER', 7: 'ALBATROSS', 8: 'ALBERTS TOWHEE', 9: 'ALEXANDRINE PARAKEET', 10: 'ALPINE CHOUGH', 11: 'ALTAMIRA YELLOWTHROAT', 12: 'AMERICAN AVOCET', 13: 'AMERICAN BITTERN', 14: 'AMERICAN COOT', 15: 'AMERICAN GOLDFINCH', 16: 'AMERICAN KESTREL', 17: 'AMERICAN PIPIT', 18: 'AMERICAN REDSTART', 19: 'AMETHYST WOODSTAR', 20: 'ANDEAN GOOSE', 21: 'ANDEAN LAPWING', 22: 'ANDEAN SISKIN', 23: 'ANHINGA', 24: 'ANIANIAU', 25: 'ANNAS HUMMINGBIRD', 26: 'ANTBIRD', 27: 'ANTILLEAN EUPHONIA', 28: 'APAPANE', 29: 'APOSTLEBIRD', 30: 'ARARIPE MANAKIN', 31: 'ASHY THRUSHBIRD', 32: 'ASIAN CRESTED IBIS', 33: 'AVADAVAT', 34: 'AZURE JAY', 35: 'AZURE TANAGER', 36: 'AZURE TIT', 37: 'BAIKAL TEAL', 38: 'BALD EAGLE', 39: 'BALD IBIS', 40: 'BALI STARLING', 41: 'BALTIMORE ORIOLE', 42: 'BANANAQUIT', 43: 'BAND TAILED GUAN', 44: 'BANDED BROADBILL', 45: 'BANDED PITA', 46: 'BANDED STILT', 47: 'BAR-TAILED GODWIT', 48: 'BARN OWL', 49: 'BARN SWALLOW', 50: 'BARRED PUFFBIRD', 51: 'BARROWS GOLDENEYE', 52: 'BAY-BREASTED WARBLER', 53: 'BEARDED BARBET', 54: 'BEARDED BELLBIRD', 55: 'BEARDED REEDLING', 56: 'BELTED KINGFISHER', 57: 'BIRD OF PARADISE', 58: 'BLACK & YELLOW  BROADBILL', 59: 'BLACK BAZA', 60: 'BLACK COCKATO', 61: 'BLACK FRANCOLIN', 62: 'BLACK SKIMMER', 63: 'BLACK SWAN', 64: 'BLACK TAIL CRAKE', 65: 'BLACK THROATED BUSHTIT', 66: 'BLACK THROATED WARBLER', 67: 'BLACK VULTURE', 68: 'BLACK-CAPPED CHICKADEE', 69: 'BLACK-NECKED GREBE', 70: 'BLACK-THROATED SPARROW', 71: 'BLACKBURNIAM WARBLER', 72: 'BLONDE CRESTED WOODPECKER', 73: 'BLUE COAU', 74: 'BLUE GROUSE', 75: 'BLUE HERON', 76: 'BLUE THROATED TOUCANET', 77: 'BOBOLINK', 78: 'BORNEAN BRISTLEHEAD', 79: 'BORNEAN LEAFBIRD', 80: 'BORNEAN PHEASANT', 81: 'BRANDT CORMARANT', 82: 'BROWN CREPPER', 83: 'BROWN NOODY', 84: 'BROWN THRASHER', 85: 'BULWERS PHEASANT', 86: 'BUSH TURKEY', 87: 'CACTUS WREN', 88: 'CALIFORNIA CONDOR', 89: 'CALIFORNIA GULL', 90: 'CALIFORNIA QUAIL', 91: 'CANARY', 92: 'CAPE GLOSSY STARLING', 93: 'CAPE LONGCLAW', 94: 'CAPE MAY WARBLER', 95: 'CAPE ROCK THRUSH', 96: 'CAPPED HERON', 97: 'CAPUCHINBIRD', 98: 'CARMINE BEE-EATER', 99: 'CASPIAN TERN', 100: 'CASSOWARY', 101: 'CEDAR WAXWING', 102: 'CERULEAN WARBLER', 103: 'CHARA DE COLLAR', 104: 'CHATTERING LORY', 105: 'CHESTNET BELLIED EUPHONIA', 106: 'CHINESE BAMBOO PARTRIDGE', 107: 'CHINESE POND HERON', 108: 'CHIPPING SPARROW', 109: 'CHUCAO TAPACULO', 110: 'CHUKAR PARTRIDGE', 111: 'CINNAMON ATTILA', 112: 'CINNAMON FLYCATCHER', 113: 'CINNAMON TEAL', 114: 'CLARKS NUTCRACKER', 115: 'COCK OF THE  ROCK', 116: 'COCKATOO', 117: 'COLLARED ARACARI', 118: 'COMMON FIRECREST', 119: 'COMMON GRACKLE', 120: 'COMMON HOUSE MARTIN', 121: 'COMMON IORA', 122: 'COMMON LOON', 123: 'COMMON POORWILL', 124: 'COMMON STARLING', 125: 'COPPERY TAILED COUCAL', 126: 'CRAB PLOVER', 127: 'CRANE HAWK', 128: 'CREAM COLORED WOODPECKER', 129: 'CRESTED AUKLET', 130: 'CRESTED CARACARA', 131: 'CRESTED COUA', 132: 'CRESTED FIREBACK', 133: 'CRESTED KINGFISHER', 134: 'CRESTED NUTHATCH', 135: 'CRESTED OROPENDOLA', 136: 'CRESTED SHRIKETIT', 137: 'CRIMSON CHAT', 138: 'CRIMSON SUNBIRD', 139: 'CROW', 140: 'CROWNED PIGEON', 141: 'CUBAN TODY', 142: 'CUBAN TROGON', 143: 'CURL CRESTED ARACURI', 144: 'D-ARNAUDS BARBET', 145: 'DARK EYED JUNCO', 146: 'DEMOISELLE CRANE', 147: 'DOUBLE BARRED FINCH', 148: 'DOUBLE BRESTED CORMARANT', 149: 'DOUBLE EYED FIG PARROT', 150: 'DOWNY WOODPECKER', 151: 'DUSKY LORY', 152: 'EARED PITA', 153: 'EASTERN BLUEBIRD', 154: 'EASTERN GOLDEN WEAVER', 155: 'EASTERN MEADOWLARK', 156: 'EASTERN ROSELLA', 157: 'EASTERN TOWEE', 158: 'ELEGANT TROGON', 159: 'ELLIOTS  PHEASANT', 160: 'EMERALD TANAGER', 161: 'EMPEROR PENGUIN', 162: 'EMU', 163: 'ENGGANO MYNA', 164: 'EURASIAN GOLDEN ORIOLE', 165: 'EURASIAN MAGPIE', 166: 'EUROPEAN GOLDFINCH', 167: 'EUROPEAN TURTLE DOVE', 168: 'EVENING GROSBEAK', 169: 'FAIRY BLUEBIRD', 170: 'FAIRY TERN', 171: 'FIORDLAND PENGUIN', 172: 'FIRE TAILLED MYZORNIS', 173: 'FLAME BOWERBIRD', 174: 'FLAME TANAGER', 175: 'FLAMINGO', 176: 'FRIGATE', 177: 'GAMBELS QUAIL', 178: 'GANG GANG COCKATOO', 179: 'GILA WOODPECKER', 180: 'GILDED FLICKER', 181: 'GLOSSY IBIS', 182: 'GO AWAY BIRD', 183: 'GOLD WING WARBLER', 184: 'GOLDEN CHEEKED WARBLER', 185: 'GOLDEN CHLOROPHONIA', 186: 'GOLDEN EAGLE', 187: 'GOLDEN PHEASANT', 188: 'GOLDEN PIPIT', 189: 'GOULDIAN FINCH', 190: 'GRAY CATBIRD', 191: 'GRAY KINGBIRD', 192: 'GRAY PARTRIDGE', 193: 'GREAT GRAY OWL', 194: 'GREAT JACAMAR', 195: 'GREAT KISKADEE', 196: 'GREAT POTOO', 197: 'GREATOR SAGE GROUSE', 198: 'GREEN BROADBILL', 199: 'GREEN JAY', 200: 'GREEN MAGPIE', 201: 'GREY PLOVER', 202: 'GROVED BILLED ANI', 203: 'GUINEA TURACO', 204: 'GUINEAFOWL', 205: 'GURNEYS PITTA', 206: 'GYRFALCON', 207: 'HAMMERKOP', 208: 'HARLEQUIN DUCK', 209: 'HARLEQUIN QUAIL', 210: 'HARPY EAGLE', 211: 'HAWAIIAN GOOSE', 212: 'HAWFINCH', 213: 'HELMET VANGA', 214: 'HEPATIC TANAGER', 215: 'HIMALAYAN BLUETAIL', 216: 'HIMALAYAN MONAL', 217: 'HOATZIN', 218: 'HOODED MERGANSER', 219: 'HOOPOES', 220: 'HORNBILL', 221: 'HORNED GUAN', 222: 'HORNED LARK', 223: 'HORNED SUNGEM', 224: 'HOUSE FINCH', 225: 'HOUSE SPARROW', 226: 'HYACINTH MACAW', 227: 'IBERIAN MAGPIE', 228: 'IBISBILL', 229: 'IMPERIAL SHAQ', 230: 'INCA TERN', 231: 'INDIAN BUSTARD', 232: 'INDIAN PITTA', 233: 'INDIAN ROLLER', 234: 'INDIGO BUNTING', 235: 'INLAND DOTTEREL', 236: 'IVORY GULL', 237: 'IWI', 238: 'JABIRU', 239: 'JACK SNIPE', 240: 'JANDAYA PARAKEET', 241: 'JAPANESE ROBIN', 242: 'JAVA SPARROW', 243: 'KAGU', 244: 'KAKAPO', 245: 'KILLDEAR', 246: 'KING VULTURE', 247: 'KIWI', 248: 'KOOKABURRA', 249: 'LARK BUNTING', 250: 'LAZULI BUNTING', 251: 'LESSER ADJUTANT', 252: 'LILAC ROLLER', 253: 'LITTLE AUK', 254: 'LONG-EARED OWL', 255: 'MAGPIE GOOSE', 256: 'MALABAR HORNBILL', 257: 'MALACHITE KINGFISHER', 258: 'MALAGASY WHITE EYE', 259: 'MALEO', 260: 'MALLARD DUCK', 261: 'MANDRIN DUCK', 262: 'MANGROVE CUCKOO', 263: 'MARABOU STORK', 264: 'MASKED BOOBY', 265: 'MASKED LAPWING', 266: 'MIKADO  PHEASANT', 267: 'MOURNING DOVE', 268: 'MYNA', 269: 'NICOBAR PIGEON', 270: 'NOISY FRIARBIRD', 271: 'NORTHERN CARDINAL', 272: 'NORTHERN FLICKER', 273: 'NORTHERN FULMAR', 274: 'NORTHERN GANNET', 275: 'NORTHERN GOSHAWK', 276: 'NORTHERN JACANA', 277: 'NORTHERN MOCKINGBIRD', 278: 'NORTHERN PARULA', 279: 'NORTHERN RED BISHOP', 280: 'NORTHERN SHOVELER', 281: 'OCELLATED TURKEY', 282: 'OKINAWA RAIL', 283: 'ORANGE BRESTED BUNTING', 284: 'ORIENTAL BAY OWL', 285: 'OSPREY', 286: 'OSTRICH', 287: 'OVENBIRD', 288: 'OYSTER CATCHER', 289: 'PAINTED BUNTING', 290: 'PALILA', 291: 'PARADISE TANAGER', 292: 'PARAKETT  AKULET', 293: 'PARUS MAJOR', 294: 'PATAGONIAN SIERRA FINCH', 295: 'PEACOCK', 296: 'PELICAN', 297: 'PEREGRINE FALCON', 298: 'PHILIPPINE EAGLE', 299: 'PINK ROBIN', 300: 'POMARINE JAEGER', 301: 'PUFFIN', 302: 'PURPLE FINCH', 303: 'PURPLE GALLINULE', 304: 'PURPLE MARTIN', 305: 'PURPLE SWAMPHEN', 306: 'PYGMY KINGFISHER', 307: 'QUETZAL', 308: 'RAINBOW LORIKEET', 309: 'RAZORBILL', 310: 'RED BEARDED BEE EATER', 311: 'RED BELLIED PITTA', 312: 'RED BROWED FINCH', 313: 'RED FACED CORMORANT', 314: 'RED FACED WARBLER', 315: 'RED FODY', 316: 'RED HEADED DUCK', 317: 'RED HEADED WOODPECKER', 318: 'RED HONEY CREEPER', 319: 'RED NAPED TROGON', 320: 'RED TAILED HAWK', 321: 'RED TAILED THRUSH', 322: 'RED WINGED BLACKBIRD', 323: 'RED WISKERED BULBUL', 324: 'REGENT BOWERBIRD', 325: 'RING-NECKED PHEASANT', 326: 'ROADRUNNER', 327: 'ROBIN', 328: 'ROCK DOVE', 329: 'ROSY FACED LOVEBIRD', 330: 'ROUGH LEG BUZZARD', 331: 'ROYAL FLYCATCHER', 332: 'RUBY THROATED HUMMINGBIRD', 333: 'RUDY KINGFISHER', 334: 'RUFOUS KINGFISHER', 335: 'RUFUOS MOTMOT', 336: 'SAMATRAN THRUSH', 337: 'SAND MARTIN', 338: 'SANDHILL CRANE', 339: 'SATYR TRAGOPAN', 340: 'SCARLET CROWNED FRUIT DOVE', 341: 'SCARLET IBIS', 342: 'SCARLET MACAW', 343: 'SCARLET TANAGER', 344: 'SHOEBILL', 345: 'SHORT BILLED DOWITCHER', 346: 'SMITHS LONGSPUR', 347: 'SNOWY EGRET', 348: 'SNOWY OWL', 349: 'SORA', 350: 'SPANGLED COTINGA', 351: 'SPLENDID WREN', 352: 'SPOON BILED SANDPIPER', 353: 'SPOONBILL', 354: 'SPOTTED CATBIRD', 355: 'SRI LANKA BLUE MAGPIE', 356: 'STEAMER DUCK', 357: 'STORK BILLED KINGFISHER', 358: 'STRAWBERRY FINCH', 359: 'STRIPED OWL', 360: 'STRIPPED MANAKIN', 361: 'STRIPPED SWALLOW', 362: 'SUPERB STARLING', 363: 'SWINHOES PHEASANT', 364: 'TAILORBIRD', 365: 'TAIWAN MAGPIE', 366: 'TAKAHE', 367: 'TASMANIAN HEN', 368: 'TEAL DUCK', 369: 'TIT MOUSE', 370: 'TOUCHAN', 371: 'TOWNSENDS WARBLER', 372: 'TREE SWALLOW', 373: 'TROPICAL KINGBIRD', 374: 'TRUMPTER SWAN', 375: 'TURKEY VULTURE', 376: 'TURQUOISE MOTMOT', 377: 'UMBRELLA BIRD', 378: 'VARIED THRUSH', 379: 'VENEZUELIAN TROUPIAL', 380: 'VERMILION FLYCATHER', 381: 'VICTORIA CROWNED PIGEON', 382: 'VIOLET GREEN SWALLOW', 383: 'VIOLET TURACO', 384: 'VULTURINE GUINEAFOWL', 385: 'WALL CREAPER', 386: 'WATTLED CURASSOW', 387: 'WATTLED LAPWING', 388: 'WHIMBREL', 389: 'WHITE BROWED CRAKE', 390: 'WHITE CHEEKED TURACO', 391: 'WHITE NECKED RAVEN', 392: 'WHITE TAILED TROPIC', 393: 'WHITE THROATED BEE EATER', 394: 'WILD TURKEY', 395: 'WILSONS BIRD OF PARADISE', 396: 'WOOD DUCK', 397: 'YELLOW BELLIED FLOWERPECKER', 398: 'YELLOW CACIQUE', 399: 'YELLOW HEADED BLACKBIRD'}
# def processed_img(img_path):
#     img=load_img(img_path,target_size=(224,224,300))
#     img=img_to_array(img)
#     img=img/255
#     img=np.expand_dims(img,[0])
#     answer=model.predict(img)
#     y_class = answer.argmax(axis=-1)
#     print(y_class)
#     y = " ".join(str(x) for x in y_class)
#     y = int(y)
#     res = lab[y]
#     print(res)
#     return res

# def run():
#     img1 = Image.open('C:\Bird_Species_Classification_Streamlit-master\personal\meta\logo1.png')
#     img1 = img1.resize((350,350))
#     st.image(img1,use_column_width=False)
#     st.title("Birds Species Classification")
#     st.markdown('''<h4 style='text-align: left; color: #d73b5c;'>* Data is based "400+ Bird Species also see 70 Sports Dataset"</h4>''',
#                 unsafe_allow_html=True)

#     img_file = st.file_uploader("Choose an Image of Bird", type=["jpg", "png"])
#     if img_file is not None:
#         st.image(img_file,use_column_width=False)
#         save_image_path = 'C:/Bird_Species_Classification_Streamlit-master/personal/upload_images/'+img_file.name
#         with open(save_image_path, "wb") as f:
#             f.write(img_file.getbuffer())

#         if st.button("Predict"):
#             result = processed_img(save_image_path)
#             st.success("Predicted Bird is: "+result)
    
# run()


















# # import sys
# # from streamlit import cli as stcli
# # import streamlit
    
# # def main():
# # # Your streamlit code

# # if __name__ == '__main__':
# #     if streamlit._is_running_with_streamlit:
# #         main()
# #     else:
# #         sys.argv = ["streamlit", "run", sys.argv[0]]
# #         sys.exit(stcli.main())